.\" Manpage for tinterm.
.\" Contact mozdrent@gmail.com.in to correct errors or typos.
.TH man 8 "27 July 2021" "devduild_alpha_0.0.1" "tinterm man page"
.SH NAME
tinterm \- a fast terminal emulator.
.SH SYNOPSIS
tinterm
.SH DESCRIPTION
tinterm is a fast terminal emulator written in C. The project is in alpha stage.
.SH OPTIONS
tinterm does not take any options.
.SH SEE ALSO
https://github.com/BeanGreen247/tinterm
.SH BUGS
.SH AUTHOR
Thomas Mozdren (mozdrent@gmail.com)
